configure.ac, src/job-manager/plugins/Makefile.am, src/job-manager/plugins/cray_pals_port_distributor.c, src/shell/Makefile.am, src/shell/plugins/Makefile.am, src/shell/plugins/cray_pals.c, t/Makefile.am, t/t1001-cray-pals.t
Moved from [flux-core#3826](https://github.com/flux-framework/flux-core/pull/3826), closes #6.
=> Shell: libpals interface plugins

src/cmd/flux-dws2jgf.py, t/data/dws2jgf/expected.jgf
Problem: Fluxion added support for properties, and
added a new required argument to some Python functions.
Solution: add empty arguments to those functions.
Also update test baseline for JGF writer.
=> DWS: update JGF writer for fluxion changes

src/modules/coral2_dws.py
Problem: workflows in Error state are immediately killed. However, that state is not always fatal.
Instead of immediately killing all jobs associated with Error workflows, only kill them after a configurable number of seconds have elapsed.
=> dws: kill workflows in error for too long

src/modules/coral2_dws.py, t/t1002-dws-workflow-obj.t
Due to some issues with Fluxion, rabbits can't be scheduled properly just yet. A workaround is needed for the systems that have rabbits currently (Tioga and Hetchy, and soon Tenaya and RZVernal). The way it works on hetchy currently is a shameless hack.
A better solution for now is to keep the scheduler ignorant of the rabbits, and make scheduling decisions based on normal factors like cores and nodes. Then, pick rabbits based on the set of compute nodes chosen.
=> Rabbit selection based on compute nodes

README.md
=> README.md: Add release number

src/shell/plugins/cray_pals.c, t/t1001-cray-pals.t
=> Unset PALS_ variables by default in shell plugin

src/modules/coral2_dws.py, t/t1002-dws-workflow-obj.t
Four more or less unrelated fixes and improvements for the coral2_dws service. All small though.
=> coral2_dws service improvements

src/shell/plugins/cray_pals.c
=> Pals debug

NEWS.md
=> news: add 0.7.0 release notes

src/job-manager/plugins/dws-jobtap.c, t/t1000-dws-dependencies.t
=> Fix dws-jobtap hang

src/shell/plugins/cray_pals.c, t/t1001-cray-pals.t
=> Non-block task placement in the cray-pals shell plugin

src/modules/coral2_dws.py
When a Workflow is deleted manually, the coral2_dws service loses its trigger to release the dws-epilog jobtap epilog action, so jobs are stuck in CLEAN while still holding resources. Adding a finalizer prevents the workflow from being deleted.
Fixes #138.
=> dws: flux finalizer

etc/flux-coral2-dws.service.in, src/modules/coral2_dws.py, t/t1002-dws-workflow-obj.t
=> dws: k8s special exitcode

NEWS.md
Problem: there are no release notes for v0.12.0.
Add them.
=> NEWS.md: add release notes for v0.12.0.

src/modules/coral2_dws.py, t/t1002-dws-workflow-obj.t
Problem: Fluxion scheduling of rabbits is unfortunately still in
flux. Particularly on elcap, where we have decided not to roll out
the JGF representation of the full resource graph while other
problems are worked out.
Add a command-line argument to disable features that require Fluxion
to have the complete JGF representation of the graph, as generated
by dws2jgf.
=> DWS: add option to disable fluxion scheduling

src/modules/coral2_dws.py
Problem: users have reported on elcap that some of their workflows hang in deletion because flux attempts to delete it without first removing the finalizer.
Add additional logic for removing Flux's finalizer from workflows.
Fixes #165.
=> dws: enforce k8s finalizer removal

src/modules/coral2_dws.py
Problem: HPE wants more info on certain workflows that hit errors and TransientCondition timeouts.
Dump the workflows to the coral2_dws logs.
The changes to the code are just to enable the extra log messages.
=> dws: dump workflows when jobs killing jobs

src/modules/coral2_dws.py
Miscellaneous log and exception improvements to satisfy my HPE overlords
=> Exception log improvements

src/modules/coral2_dws.py, src/python/flux_k8s/directivebreakdown.py, t/t1002-dws-workflow-obj.t
Problem: Flux does not handle workflows that require Lustre MGTs,
or more specifically any DirectiveBreakdown with an allocation type
of 'AllocateSingleServer'. However, Flux handles MDTs and other
allocations which have a 'count' constraint of 1, which is the same
thing effectively.
Handle 'AllocateSingleServer' allocations the same way that 'count'
constraints are handled (see #181 ), which is to pick a single rabbit and
place the allocation there, ignoring Fluxion's allocation choices
somewhat.
Fixes #186 .
=> DWS: handling for Lustre MGTs

t/data/dws2jgf/expected-compute-01-04.jgf, t/data/dws2jgf/expected-compute-01-nodws.jgf, t/data/dws2jgf/expected-compute-01.jgf, t/data/dws2jgf/expected-properties.jgf
Problem: https://github.com/flux-framework/flux-sched/pull/1286 changed the way edges
are represented in JGF.
Update the expected JGF output of flux-dws2jgf.
=> Update expected jgf

src/modules/coral2_dws.py
Problem: HPE recently changed the way `Storage` resources have their `status` field populated, so it is no longer guaranteed that the field exists.
Ignore the field if it cannot be found.
=> dws: ignore nonexistent rabbit status field

NEWS.md
Tacked on top of #215 . Will rebase to drop those commits once it goes in.
=> Release v0.17.0

NEWS.md
=> News v0.17.1

t/t1002-dws-workflow-obj.t
Problem: flux-framework/flux-sched/issues/1284 came up in production and was not caught beforehand because the testsuite never exhausts the available rabbit resources.
Add a test that runs three back-to-back 10TiB rabbit jobs to exhaust all the rabbit resources.
=> testsuite: add a test for big rabbit jobs

NEWS.md
=> NEWS.md: add release notes for v0.18.0

src/python/flux_k8s/watch.py
Fixing problems raised by @roehrich-hpe and @bdevcich in PR #247 .
=> Watch resourceversion fix

NEWS.md
Problem: there are no release notes for v0.19.0.
Add them.
=> NEWS.md: add release notes for v0.19.0

src/job-manager/plugins/dws-jobtap.c, src/modules/coral2_dws.py, t/dws-dependencies/coral2_dws.py, t/t1000-dws-dependencies.t
Problem: coral2_dws does not have a way to make a workflow jump to
Teardown, which may sometimes be necessary.
Add an RPC that moves workflows to Teardown.
Fixes #255.
=> dws: cancel data movement, move workflow to Teardown

src/modules/coral2_dws.py, t/t1003-dws-nnf-watch.t
Problem: in theory, if a rabbit-to-compute-node PCIe link goes down,
coral2_dws will drain the node. However, admins have generally
disabled that feature for being disruptive to non-rabbit users.
PR https://github.com/flux-framework/flux-coral2/pull/265 introduced a non-intrusive way to avoid scheduling rabbit
jobs on specific nodes, by tagging nodes with a property. This
could be used to cover the PCIe link failure case as well.
If draining is disabled, unless the `rabbit.soft_drain` config
option is set to `false`, mark nodes with a failed PCIe link
with the `badrabbit` property.
=> dws: add option to tag compute nodes instead of draining

src/modules/coral2_dws.py, t/t1003-dws-nnf-watch.t
Fixes two separate but related issues, described in the first two commit messages.
=> dws: remove-property fix

src/modules/coral2_dws.py
Pylint found a handful of problems with `coral2_dws.py`, including undefined variables and unused code paths, in addition to some less harmful things like unideal log formatting.
=> dws: linting, fix undefined variable

configure.ac, src/Makefile.am, src/common/Makefile.am, src/common/libtap/Makefile.am, src/common/libtap/tap.c, src/common/libtap/tap.h
Problem: flux-coral2 doesn't have the libtap framework for unit tests.
Pull it in from flux-core.
There aren't any users yet.
=> libtap: add unit testing framework

src/job-manager/plugins/dws-jobtap.c
Problem: often, the dws-jobtap plugin does not report what jobid it hits an error on. This can make debugging hard.
Add job ids to the error messages.
=> dws: add jobid to jobtap error messages

src/python/flux_k8s/workflow.py, t/Makefile.am
Stacked on top of #291.
Fixes #292 .
=> Fix keyerror

src/modules/coral2_dws.py, src/python/flux_k8s/Makefile.am, src/python/flux_k8s/crd.py, src/python/flux_k8s/storage.py, src/python/flux_k8s/watch.py, src/python/flux_k8s/workflow.py
Problem: `coral2_dws.py` is too long and complicated and should have
its functionality broken up.
Break out functionality related to monitoring `Storage` resources
into a separate module.
=> dws: storage refactor

src/job-manager/plugins/dws-jobtap.c, src/modules/coral2_dws.py, src/python/flux_k8s/directivebreakdown.py, t/t1002-dws-workflow-obj.t
=> dws: fix dependency error

doc/Makefile.am, doc/guide/admin.rst, doc/guide/glossary.rst, doc/index.rst, doc/test/spell.en.pws, doc/test/spellcheck
Here's a bit more documentation.
=> doc: add admin guide and glossary

doc/guide/glossary.rst, doc/guide/reference.rst, doc/index.rst, doc/test/spell.en.pws, doc/test/spellcheck
Just some incremental documentation improvements.
=> doc: add references, system list

src/cmd/flux-dws2jgf.py, t/Makefile.am, t/data/dws2jgf2/rabbitmapping.json, t/data/dws2jgf2/resource.toml, t/t2002-dws2jgf2.t
=> dws2jgf: fix properties on nodes not in DWS

src/job-manager/plugins/dws-jobtap.c, src/modules/coral2_dws.py, t/t1002-dws-workflow-obj.t
Problem: the `dws.teardown` RPC handler in `coral2_dws` does not
check whether the workflow exists before trying to move it to
Teardown. However, if a user cancels a job repeatedly shortly after
submission, the workflow may not be created before the `dws.teardown`
RPC is sent.
Make the RPC handler check for workflow existence.
=> dws: fix teardown cb

src/job-manager/plugins/dws-jobtap.c, t/dws-dependencies/coral2_dws.py, t/t1000-dws-dependencies.t, t/t1002-dws-workflow-obj.t
=> dws: fix add-constraint logic

src/python/flux_k8s/crd.py, src/python/flux_k8s/directivebreakdown.py, src/python/flux_k8s/workflow.py, t/data/breakdown/lustre10tb_daemon.yaml
=> dws: update to use `v1alpha3`

.github/workflows/main.yml, src/test/docker/docker-run-checks.sh, src/test/generate-matrix.py
This repo's CI is inflexible and shallow. Add a generate-matrix script, copying it from flux-sched, as a first step to improve it.
=> ci: generate matrix

src/python/flux_k8s/cleanup.py
Problem: on Hetchy, Flux failed to remove finalizers from a workflow due to a race condition. The workflow had already been deleted, perhaps manually, and attempts to remove the finalizer failed because the `remove_finalizer` function was using an old version of the workflow with finalizers that had already been removed. Therefore, the calls to patch the workflow to remove the Flux finalizer were seen by kubernetes as an attempt to *add* finalizers, which is not allowed if the workflow has been deleted, and a 422 error code was returned.
Rename the old `remove_finalizer` to `_remove_finalizer` and add a new exception-catching function `remove_finalizer` that wraps `_remove_finalizer`, fetching the latest workflow and trying again.
=> dws: catch remove-finalizer exception and retry

src/modules/coral2_dws.py, t/t1002-dws-workflow-obj.t
Problem: in order to support the new style of rabbit data movement,
Flux needs to grab a kubernetes secret for certain workflows, and
then export it to jobs as an environment variable.
Grab the secret and pack it into the prolog-remove RPC for it to
be set in the job's environment by the job shell.
Fixes https://github.com/flux-framework/flux-coral2/issues/256.
=> dws: secret token for copy-offload

NEWS.md
Problem: there are no release notes for v0.23.0.
Add them.
=> NEWS.md: add release notes for v0.23.0

src/modules/coral2_dws.py, src/python/flux_k8s/cleanup.py, src/python/flux_k8s/workflow.py, t/Makefile.am, t/python/t0003-coral2-dws.py
=> dws: rabbit presets fixes

NEWS.md
Problem: there are no release notes for v0.23.1.
Add release notes.
=> NEWS.md: add release notes for v0.23.1

t/t1002-dws-workflow-obj.t
Problem: `t1002` is very long and complicated, and some simple refactoring would improve it a lot.
=> test: workflow tests refactor

doc/guide/rabbit.rst, doc/guide/rabbit_config.rst, doc/test/spell.en.pws, src/modules/coral2_dws.py, src/python/flux_k8s/directivebreakdown.py, src/python/flux_k8s/workflow.py, t/scripts/coral2_inspection.py, t/t1002-dws-workflow-obj.t
As described in #364, some rabbit jobs would benefit from the ability to tolerate lost nodes.
Fixes #364.
=> dws: allow jobs to tolerate lost nodes and/or rabbits

src/shell/plugins/dws_environment.c
Problem: `dws_environment.c` waits for an event in a job's eventlog, but there is a utility function for doing so.
Use the common utility function.
=> shell: use eventlog_wait_for in dws_environment.c
