- src/shell/plugins/cray_pals.c
Problem: Future versions of flux-core will require FLUX_SHELL_PLUGIN_NAME
to be defined when including `flux/shell.h` or compilation will fail.
Set FLUX_SHELL_PLUGIN_NAME to "libpals" for the cray_pals shell plugin
and use this definition to set the plugin name.
> shell/plugins: add FLUX_SHELL_PLUGIN_NAME to cray_pals plugin

- src/job-manager/plugins/cray_pals_port_distributor.c
- src/shell/plugins/cray_pals.c
- t/t1001-cray-pals.t
This PR adds better synchronization between the cray-pals shell plugin and the port-distributor jobtap plugin as discussed in #16. The jobtap plugin now emits the `cray_port_distribution` event under a `prolog` action, allowing the shell plugin to definitively detect a missing jobtap plugin if this event does not appear before the `start` event.
This means the shell plugin can be loaded without the jobtap plugin and jobs will still run successfully (e.g. if running the flux-sched testsuite)
One minor issue: This change doesn't prevent the shell plugin from setting most of the libpals environment variables (besides `PMI_CONTROL_PORT`) and writing out the apinfo file, since these actions happen before the plugin fetches the `cray_port_distribution` event. I figure this isn't a critical …
> cray-libpals: allow shell plugin to detect missing port-distributor jobtap plugin

- Makefile.am
Problem: running 'make dist' requires a pylintrc file which
cannot be built and does not exist.
Solution: remove the file from the requirements.
> build: remove pylintrc dist requirement

- src/job-manager/plugins/cray_pals_port_distributor.c
- t/t1001-cray-pals.t
Ryan ran into an issue on Tioga where he added an additional 0 when configuring the port-distributing plugin, and it gave him a rather opaque MPI error, so I thought it would be good to add some simple port-validating logic to the plugin.
> Port validation

- src/shell/plugins/cray_pals.c
- t/t1001-cray-pals.t
Problem: the libpals shell plugin does not account for task counts
not specified in the usual task-count jobspec position. For instance,
it does not count tasks specified with the per-resource.* shell options.
Solution: properly count tasks by checking the counts given by the shell
rather than the counts given in the jobspec.
Fixes https://github.com/flux-framework/flux-coral2/issues/27.
> Pals incorrect task counts

- t/scripts/apinfo_checker.py
- t/t1001-cray-pals.t
Problem: there are no tests for the contents of the apinfo file.
Solution: add a script that can read the contents and print them as JSON for testing.
> cray-pals: add apinfo content tests

- src/shell/plugins/Makefile.am
Problem: flux-coral2 is being added to mainline TOSS. The cray-pals plugin is built into the main shell pluginpath, so it is loaded by default. This introduces some performance overhead.
Solution: move the shell plugin install directory into a subdirectory of the shell pluginpath so it is not
loaded by default.
> build: change shell plugin install directory

- src/shell/plugins/Makefile.am
Problem: a header file is missing from the build system, and it is not included in distributions.
Add the missing file.
> build: add missing header file

- src/modules/coral2_dws.py
Problem: dws-workflow-test-JOBID names
are long and it isn't clear that the jobid is
in fact a flux job ID.
Rename workflows created by flux for clarity.
> dws: change workflow names

- src/modules/coral2_dws.py
Problem: some error messages are logged which do not include the jobid, making it difficult or impossible to figure out which job is associated with the error.
> dws: add jobid to RPC error message

- src/job-manager/plugins/dws-jobtap.c
- t/Makefile.am
- t/dws-dependencies/coral2_dws.py
- t/t1000-dws-dependencies.t
Flux jobs with rabbit file systems should be held in jobtap epilog while data movement is completed. Add an epilog to the dws-jobtap plugin and associated tests.
> Dws jobtap epilog

- t/t1000-dws-dependencies.t
- t/t1001-cray-pals.t
- t/t1002-dws-workflow-obj.t
- t/t1003-dws-nnf-watch.t
Problem: 'flux mini CMD' is deprecated in favor of 'flux CMD'.
Replace usage in the test suite.
> test: replace 'flux mini' usage

- src/job-manager/plugins/dws-jobtap.c
- t/dws-dependencies/coral2_dws.py
- t/t1000-dws-dependencies.t
dws-jobtap.c adds jobtap prologs and epilogs to hold jobs in a state while data is moved to rabbits (the prolog) and from them (the epilog). If a severity-0 exception occurs during the prolog, the prolog should be removed immediately rather than waiting for the data movement to complete. However, there are no tests for that functionality. Also, epilogs are currently removed from jobs when exceptions occur, but there is no reason for that to be done, since the epilog runs once the job has already finished.
> Dws prolog exceptions

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- t/data/workflow-obj/two_directives.json
- t/t1002-dws-workflow-obj.t
The first two commits are minor tweaks to improve error messages.
Requests for rabbit storage are strings that look like `#DW jobdw capacity=10GiB type=xfs name=project1`. The strings go either as a string or a list of strings into jobspec `attributes.system.dw`. Users might therefore do something like `flux submit --setattr=system.dw="#DW jobdw capacity=10KiB type=xfs name=project1" -n1 sleep 15`. If they want multiple directives (which will be common) they currently need to do something like `flux submit --setattr=^system.dw="xfs_copy_in.json"` where `xfs_copy_in.json` is a JSON file containing a list of DW directives. 
By splitting DW directives across lines, we can allow users to write things like `flux submit --setattr=system.dw="#DW jobdw capacity=10KiB type=xfs name=project1 \n #DW …
> Split DW directives across lines

- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/t1002-dws-workflow-obj.t
Workflows that are stuck in "State: Error" should be killed off after a configurable number of seconds. But the logic for doing so is broken. Fix the logic and add a test.
> Fix workflow error handling

- Makefile.am
- configure.ac
- etc/01-coral2-rc
- src/shell/plugins/Makefile.am
- src/shell/plugins/cray_pals.c
- t/t1001-cray-pals.t
This resolves #52 by adding an rc script that loads the port distributor jobtap plugin in all instances.
In addition it makes a slight tweak to the cray_pals plugin so that it conforms to the way the `pmi` shell option is being changed in flux-core, as described in flux-framework/flux-core#5063.
These changes assume that `flux-coral2` is built with the same prefix as `flux-core`.
Also, we'll want to ask the sys admins to
1) drop the job manager config in the system instance that loads the port distributor plugin
2) drop the change to the shell initrc.lua that loads the cray_pals plugin from its side-installed location
3) add a change to the shell initrc.lua to add `cray-pals` to the default set of PMIs offered to jobs
The last one looks like this
```lua
-- Add cray-pals to the default …
```
> load port distributor in all Flux instances, and support -o pmi=cray-pals

- etc/flux-coral2-dws.service.in
Problem: the coral2-dws systemd service 'requires' flux which means (in combination with 'Restart=always') that the flux service cannot be shut down without first shutting down the coral2-dws service. That is obnoxious.
Solution: change 'requires' to 'bindsto' which is
a looser requirement.
Fixes #59.
> systemd: change Requires to BindTo

- src/shell/plugins/Makefile.am
- t/Makefile.am
- t/t1004-dws-environment.t
Problem: the dws_environment shell plugin is not
loaded by default. The plugin has no effect when
a job has no DW string, so there is no drawback
to always loading it.
Install the plugin to the shell plugin dir, not
a subdirectory.
> dws: install shell plugin to main dir

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: coral2_dws.py splits DW strings by
newlines. This generally works, but is restrictive.
Split DW strings by the '#DW ' token. This should
prove both more robust and more flexible.
> dws: split directives by DW token

- config/ax_flux_core.m4
Problem: the cray-pals shell plugin parses the pmi shell option as a list of PMI implementations and if it doesn't find itself in the list, it is disabled. However, in flux-core versions prior to 0.49.0, the pmi shell plugin throws an error if the pmi shell option does not contain options it recognizes.
Require flux-core >= 0.49.0 at configure time.
Fixes #65
> build: require flux-core >= 0.49.0

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
The coral2_dws script runs as a systemd service as the flux user, but needs access to kubernetes. Access to kubernetes is generally achieved with [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/). Brian Behlendorf told me that placing the kubeconfig in the flux user's home directory (where kubernetes looks by default) would be inconvenient and that allowing the service's kubeconfig to be configured with a command-line argument would be ideal.
> DWS kubeconfig command-line option

- NEWS.md
Problem: there are no release notes for 0.5.0.
Add them.
> NEWS.md: add 0.5.0 release notes

- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/t1002-dws-workflow-obj.t
Add support and tests for persistent rabbit allocations---i.e., rabbit allocations that are independent of jobs.
> Persistent dw directives

- src/job-manager/plugins/cray_pals_port_distributor.c
- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/dws-dependencies/coral2_dws.py
- t/python/t0001-directive-breakdown.py
- t/t1000-dws-dependencies.t
- t/t1002-dws-workflow-obj.t
This PR is a substantial rewrite of `dws-jobtap.c` and `coral2_dws.py` to solve the problem of handling `coral2_dws.py` crashes. Before this PR is merged, the `coral2_dws.py` service assumes that its lifetime encompasses the lifetime of any job that it sees. It can't handle rabbit jobs that existed before it started. This is because it keeps an internal data structure of active rabbit jobs, and jobs can only be added to the data structure when they are being created. 
Furthermore, the `dws-jobtap.c` plugin sends a RPC to `coral2_dws.py` when a job is ready (by flux-core standards) to transition states, and `coral2_dws.py` responds to that RPC when HPE rabbit software gives the go-ahead. But HPE rabbit software can take a considerable amount of time to give the go-ahead. If the …
> DWS service crashes

- src/job-manager/plugins/cray_pals_port_distributor.c
- src/shell/plugins/cray_pals.c
- t/t1001-cray-pals.t
This is a partial resolution of #79. The only new variable set is `PMI_SHARED_SECRET`. Some additional variables are unset.
We could set more variables listed in #79, but only `PMI_SHARED_SECRET` has resulted in an error.
> Cray pals env vars

- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/data/breakdown/lustre10tb.yaml
- t/data/breakdown/xfs10gb.yaml
- t/python/t0001-directive-breakdown.py
The first step towards making resource requests that match the resource graph built in #88 is to create jobspecs with top-level "rack" resources. This PR adds logic for building such jobspecs.
> Jobspec manipulations

- .mergify.yml
Problem: mergify is configured to require status
checks to pass before merging, but we can use
GitHub's branch protections instead.
Remove mergify's status checks requirements.
> mergify: remove status check requirement

- src/modules/coral2_dws.py
HPE has updated how workflows report errors:
> 
> The short of it is that workflow.status.status == "Error"  Indicates a fatal error
> 
> workflow.status.status == "TransientCondition"  Indicates an error that may recover
> Dws fatal error handling

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/t1002-dws-workflow-obj.t
The final piece after #88, #89, and #90 for getting rabbit allocations through Fluxion. The logic for building a resource graph with rabbits is there already, and so is the logic for creating jobspecs which request rabbits. But at the moment the scheduler never actually gets to see the jobspecs that request rabbits, because the plugins hold them back. This PR fixes that.
It also fixes (or at least minimizes) a major limitation of the previous implementation's handling of lustre file systems, which stuck each lustre allocation on a single rabbit. Now lustre file systems are split across rabbits by default.
> Fluxion scheduling for rabbits

- etc/01-coral2-rc
Problem: If BASH_ENV is set to a script that is not errexit clean, the 01-coral2-rc script may immediately.
Drop -e from the shebang and add a "set -e" afterwards.
Fixes #95
> rc: call set -e after shebang in 01-coral2-rc

- etc/01-coral2-rc
Problem: 01-coral2-rc has a bash shebang, but when a user sets BASH_ENV, it potentially sources unnecessary stuff.
Switch to a posix shebang.
Re-add the -e since this also fixes #95.
Sorry I shouldn't have let that last PR go in.  The solution kind of changed to this better one right about then.
> rc: use posix shell

- k8s/flux-test-storage0.yaml
- k8s/flux-test-storage1.yaml
- src/cmd/flux-dws2jgf.py
- src/python/flux_k8s/crd.py
- t/sharness.d/03-kube.sh
Problem: HPE updates the group of various kubernetes objects from 'dws.cray.hpe.com' to 'dataworkflowservices.github.io'. This breaks code that is looking for resources under the former group.
Update the group to the new name.
> dws: fix group of k8s crds

- NEWS.md
Problem: there are no release notes for 0.8.0.
Add them.
> NEWS: add 0.8.0 release notes

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- src/shell/plugins/Makefile.am
- src/shell/plugins/dws_environment.c
- t/dws-dependencies/coral2_dws.py
- t/t1000-dws-dependencies.t
- t/t1004-dws-environment.t
As discussed in #104, export the hostname of the rabbit local to each compute node as the FLUX_LOCAL_RABBIT environment variable.
> Rabbit env vars

- src/test/docker/el8/Dockerfile
Problem: the el8 container build fails because an updated pip expects a more recent version of python than is provided (which is 3.6) when installing the kubernetes package.
Remove a line which upgrades pip to a newer version, keeping the old version is compatible with Python 3.6.
Fixes #111.
> docker: fix kubernetes install

- NEWS.md
Marty McFadden would like to start using the `FLUX_LOCAL_RABBIT` environment variable so I thought it was time to make a new release.
> NEWS: add 0.8.1 release notes

- src/modules/coral2_dws.py
- t/data/nnf-watch/down.yaml
- t/data/nnf-watch/up.yaml
- t/t1002-dws-workflow-obj.t
- t/t1003-dws-nnf-watch.t
Leverages functionality provided by [this flux-sched PR](https://github.com/flux-framework/flux-sched/pull/1110) to mark rabbits up or down based on status reported by Kubernetes 'Storage' objects.
> Draining rabbits

- src/cmd/flux-dws2jgf.py
- t/data/dws2jgf/expected-compute-01-04.jgf
- t/data/dws2jgf/expected-compute-01-nodws.jgf
- t/data/dws2jgf/expected-compute-01.jgf
- t/scripts/set_status.py
- t/t2000-dws2jgf.t
WIP until Fluxion is updated to support a `status` parameter to the `FluxionResourcePoolV1 class. 
Edit: done.
> Initialize rabbits as down

- src/shell/plugins/cray_pals.c
- t/t1001-cray-pals.t
Problem: it was proposed in flux-framework/flux-core#5714 that we should add the Flux PMI libdir to LD_LIBRARY_PATH in the job environment to improve the user experience, but that would break the `cray-pals` plugin which wouldn't be used if Cray MPICH finds Flux's `libpmi2.so` before its own.
In `cray-pals`, if LD_LIBRARY_PATH is found to include the Flux PMI libdir, edit it out.
> cray-pals: edit LD_LIBRARY_PATH to avoid Flux libpmi2.so

- NEWS.md
Problem: there are no release notes for release v0.10.0.
Add them.
> NEWS.md: add v0.10.0 release notes

- configure.ac
Problem: LC EAS3 clusters have the python kubernetes package version 11.0.0, not anything higher.
The code appears to work with version 11, so downgrade the required version to 11.
> configure: downgrade required kubernetes version

- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/python/t0001-directive-breakdown.py
- t/t1000-dws-dependencies.t
- t/t1002-dws-workflow-obj.t
This PR fixes one problem with rabbit allocations and alleviates another problem.
The fixed problem is that rabbit allocations have an implicit minimum size: allocations smaller than around 2 GiB fail or hang. Fix this by enforcing a configurable minimum size that defaults to 4GiB.
The alleviated problem is that lustre allocations are always split `N` ways for `N` the number of compute nodes. This means that sometimes a single rack will have many lustre allocations on it for a single job and lustre file system, when ideally all those allocations would be combined into one, thus saving some NVMe namespaces. However, this is a bit tricky due to the way DWS requires allocations to be specified; it's impossible to specify an allocation size for one rack independent of the size of the …
> dws: enforce minimum rabbit allocation size

- src/modules/coral2_dws.py
- t/data/nnf-watch/rabbit-jobspec.json
- t/t1003-dws-nnf-watch.t
Problem: the tests for watching rabbit status rely on checking logs
for specific messages. This is a difficult and unreliable form of
testing.
Add more thorough tests checking that rabbits are in fact marked as
down by Fluxion--when the corresponding K8s Storage object is marked
as down--by submitting rabbit resource requests.
> test: fix rabbit watch test failures

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Fluxion should reject jobs that request an infeasible amount of rabbit storage. However, [this commit](https://github.com/jameshcorbett/flux-coral2/commit/297f1fc167e00f353016e26333a3d33a85c54e68) disabled Fluxion scheduling of rabbits. Revert that commit, fix a problem with reverting that commit, and add a test for the expected behavior.
> test: request too much rabbit storage

- src/cmd/flux-dws2jgf.py
- src/modules/coral2_dws.py
- t/data/dws2jgf/expected-compute-01-04.jgf
- t/data/dws2jgf/expected-compute-01-nodws.jgf
- t/data/dws2jgf/expected-compute-01.jgf
- t/t2000-dws2jgf.t
El Capitan currently only has rabbit nodes and gateway nodes, no compute nodes. This makes testing the rabbits difficult. The best we can do for now is to treat rabbit nodes as compute nodes. This requires some changes to how the Fluxion resource graph is built for rabbits.
I think once El Capitan gets a couple dozen compute nodes, this won't be useful any more.
> dws2jgf: rabbits as compute nodes

- src/cmd/flux-dws2jgf.py
- t/data/dws2jgf/R-properties
- t/data/dws2jgf/expected-compute-01-04.jgf
- t/data/dws2jgf/expected-compute-01.jgf
- t/data/dws2jgf/expected-properties.jgf
- t/t2000-dws2jgf.t
Problem: flux-dws2jgf writes out vertex properties as a python list,
but Fluxion's JGF reader expects a JSON object.
Write out properties as keys in a mapping with empty string values.
See also https://github.com/flux-framework/flux-sched/pull/1149.
> dws2jgf: fix node attributes

- NEWS.md
Problem: there are no release notes for flux-coral2 v0.11.0.
Add them.
> NEWS.md: add release notes for v0.11.0

- src/job-manager/plugins/dws-jobtap.c
- t/dws-dependencies/coral2_dws.py
- t/rc/rc1-job
Problem: the `dws-jobtap` plugin has a race condition in its exception-raising logic.
> dws-jobtap: fix race conditions with exception-raising

- t/data/dws2jgf/expected-compute-01-04.jgf
- t/data/dws2jgf/expected-compute-01-nodws.jgf
- t/data/dws2jgf/expected-compute-01.jgf
- t/data/dws2jgf/expected-properties.jgf
With https://github.com/flux-framework/flux-sched/pull/1149, Fluxion has updated the way it writes out vertex properties. It now writes them out (correctly) as a mapping instead of a list.
Update the expected JGFs generated by flux-dws2jgf.
> test: update expected JGF after fluxion update

- src/modules/coral2_dws.py
- t/t1003-dws-nnf-watch.t
Problem: compute nodes can lose their link with their local rabbit. If that happens, the node should be drained with a reasonable message so admins can investigate.
Kubernetes Storage resources list the status of the links between rabbits and their compute nodes. Watch the status and drain nodes if their status changes to 'Offline'.
Fixes #139 .
> dws: add support for draining Offline nodes

- src/modules/coral2_dws.py
- t/t1003-dws-nnf-watch.t
#140 made the coral2-dws service aggressively drain nodes. Add an option to disable that functionality.
> dws: add option to disable draining

- src/cmd/flux-dws2jgf.py
- src/modules/coral2_dws.py
Problem: flux-dws2jgf assumes storages always have a
`.status.access.computes` field, but recent experience on rzvernal
has shown this to be false.
Make .status.access.computes optional.
> Handle rabbits with no computes

- src/modules/coral2_dws.py
Problem: coral2_dws tries to strip a 'rabbit-' prefix from the names
of rabbit vertices it finds in JGF. However, it uses the str.strip()
method incorrectly and in fact strips the characters 'r', 'a', 'b',
'i', 't', and '-' from the beginning and end of the rabbit name.
Strip the prefix correctly.
> dws: fix rabbit name manipulation logic

- src/modules/coral2_dws.py
- src/python/flux_k8s/watch.py
- t/t1002-dws-workflow-obj.t
Problem: while watching for k8s resources, a resourceversion > 0
is required. When there are only old resources lying around and
no new ones, the resourceversion will be > 0 but too old for
kubernetes to accept it, and an exception may be raised.
Catch the exception and set the resource version to 0.
> k8s watch exception handling

- src/test/docker/docker-run-checks.sh
Problem: flux-core and -sched both have docker-run-checks scripts that mount the $HOME directory as $HOME, not as /home/$USER (as this project does).
Change to be consistent with those projects.
> docker: mount $HOME as $HOME

- src/cmd/flux-dws2jgf.py
- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/data/dws2jgf/expected-compute-01-04.jgf
- t/data/dws2jgf/expected-compute-01-nodws.jgf
- t/data/dws2jgf/expected-compute-01.jgf
- t/data/dws2jgf/expected-properties.jgf
- t/data/dws2jgf/rabbit-jobspec.json
- t/data/nnf-watch/rabbit-jobspec.json
- t/python/t0001-directive-breakdown.py
- t/t1002-dws-workflow-obj.t
- t/t1003-dws-nnf-watch.t
- t/t2000-dws2jgf.t
As noted [here](https://github.com/flux-framework/flux-sched/discussions/1189), the existing Fluxion graph layout imposes a serious limitation on scheduling: every node is forced to be on a different rack.
By changing the resource graph to remove intermediate "rabbit" vertices between "rack" and "ssd", this limitation can be worked around. It also opens up possibilities for better Fluxion scheduling of lustre-only rabbit jobs.
> Resource graph: rack-parent ssds

- src/test/docker/docker-run-checks.sh
PR #154 was opened too hastily. By default, `kubectl` (which is used all over the place in flux-coral2 tests) looks for a kubeconfig file in `$HOME/.kube/config`. And the flux-coral2 testsuite has logic in place, such as [here](https://github.com/flux-framework/flux-coral2/blob/master/t/sharness.d/03-kube.sh), to manipulate kubernetes into working properly which was affected by PR #154. It caused test failures which were only visible when running with kubernetes (which CI doesn't do).
The changes introduced by #154 are still desirable (see issue #156), but they will need to be introduced with more extensive changes which hopefully would make the kubernetes manipulations more straightforward.
> Revert docker home mount and change hostname

- NEWS.md
Problem: there are no release notes for v0.13.0.
Add them.
> NEWS.md: add release notes for v0.13.0

- src/cmd/flux-dws2jgf.py
- t/data/dws2jgf/expected-compute-01-nodws.jgf
- t/data/dws2jgf/expected-properties.jgf
- t/t2000-dws2jgf.t
Problem: at the moment admins should supply the name of the cluster through a command-line argument when running dws2jgf. But they will probably run it from the management node of a cluster, and most LC clusters have nodes with names like 'nameXXXXX' for XXXXX some decimal number.
Simplify things for them by making the cluster name in the resource graph default to the hostname stripped of numerals.
> dws2jgf: change cluster-name logic

- src/python/flux_k8s/watch.py
Problem: some older versions of kubernetes do not have a 'kubernetes.client.exceptions' module which 'watch.py' attempts to import from.
Add a try/except around the import, and if the import fails, create a dummy exception with the same name.
> dws: change exception import path

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: if a workflow goes to status: Error, coral2_dws will raise
an exception. For most states the exception will transition the job
to CLEANUP, which eventually moves the workflow to Teardown.
However, if the job is already in CLEANUP and is being held in the
dws-epilog epilog when the exception is thrown, the exception has
no effect and the epilog will never be finished because the workflow
does not progress.
If a workflow moves to status: Error in PostRun or DataOut states,
move it directly to Teardown.
> dws: fix Postrun workflow error hang

- src/modules/coral2_dws.py
- t/t1003-dws-nnf-watch.t
As mentioned in #172, it would be able to restrict coral2-dws's draining functionality to only specific queues.
> DWS: queue-specific draining

- NEWS.md
Problem: there are no release notes for v0.14.0.
Add them.
> NEWS.md: add release notes for v0.14.0

- src/modules/coral2_dws.py
- src/python/flux_k8s/crd.py
- t/t1002-dws-workflow-obj.t
Problem: my HPE overlords want the coral2-dws service to log `nnfdatamovements`.
> dws: dump datamovements to logs

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/data/breakdown/lustre10tb_daemon.yaml
- t/dws-dependencies/coral2_dws.py
- t/python/t0001-directive-breakdown.py
- t/t1002-dws-workflow-obj.t
Problem: There is no marker that a job needs the nnf data movement
daemon to be running during its duration. Without a marker, an
administrative prolog cannot tell whether to start the daemon.
Add a boolean to the dws-environment event that indicates whether
the nnf-dm daemon is needed. The administrative prolog can watch for
this event and its context.
Fixes #167.
@grondo, what would be the best way for a shell script (the administrative prolog) to watch for the boolean? It is already watching for the `dws_environment` event, but now it also needs to know whether the `copy-offload` entry in the context is true or false.
> dws: add marker for prolog to enable the nnf-dm daemon

- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
Problem: as described in #171, creating many MDTs is a bad
for performance, and usually goes against what is explicitly
required by directivebreakdown resources. However, there is not
yet a good way to get Fluxion to handle MDT allocation.
Bypass Fluxion allocation completely, and tell DWS to create
exactly the number of allocations requested in the
.constraints.count field (which is usually found on MDTs).
Place the allocations on the rabbits which have the most compute
nodes allocated to the job.
This is intended to be only a temporary solution, since it
adds a new potential problem, in that some rabbit storage is
used which is not tracked by Fluxion. This could lead to
overallocation of resources, causing jobs to fail with errors.
However, this seems unlikely to occur in practice, …
> dws: crudely enforce mdt count constraints

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: the flux-coral2 script adds a memo to rabbit jobs with a JSON list of the rabbits used. This is inconvenient and can potentially become large.
Use a hostlist instead.
> dws: change rabbit memo to hostlist

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: HPE and others working with k8s workflows have been
frustrated that k8s resources disappear shortly after their
associated flux job moves to cleanup, and have requested that
Flux save some of the resources.
Save workflow resources to jobs' KVS. More resources may be needed
in the future, but start small to reduce KVS pressure.
See also #180 .
> dws: saving workflows to KVS

- NEWS.md
Problem: there are no release notes for v0.15.0.
Add them.
> NEWS.md: add v0.15.0 release notes

- src/modules/coral2_dws.py
- src/python/flux_k8s/crd.py
Problem: No NnfDataMovement resources are found when dumping to the
journal. The current implementation is only looking at the default
namespace instead of all namespaces. Additionally, the output is valid
json.
- Changed the api call to use `list_cluster_custom_object` to retrieve
objects from all namespaces
- Deleted `DATAMOVEMENT_CRD` since namespace cannot be used for
`list_cluster_custom_object`
- Moved NnfDatamovement retrieval to before the transition to
`TearDown`. Otherwise these will start to be removed.
> dws: Fix NnfDataMovement logging

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Two changes:
1) Save workflows to the KVS after the completion of every state except Teardown. So now you don't need to wait for the job to complete to look at your workflow
2) Save the `.status.elapsedTimeLastState` field of workflows to the KVS after the completion of every state except Teardown. The timing goes under the `rabbit_{state}_timing` key so to get the timing for DataIn, you could run `flux job info $JOBID rabbit_DataIn_timing`.
> Kvs workflow timings

- NEWS.md
Problem: there are no release notes for v0.16.0.
Add them.
Waiting on #189 .
> NEWS.md: add release notes for 0.16.0

- src/shell/plugins/dws_environment.c
Problem: as described in issue #192, on large, busy systems with lots of jobs, the dws_environment shell plugin's two-second timeout to fetch the first eventlog entry is too short and occasionally times out.
In Mark Grondona's tests to reproduce the issue, all succeeded within five seconds. However, to be safe, increase the timeout to thirty seconds.
Fixes #192.
> dws: increase timeout of shell plugin

- src/modules/coral2_dws.py
- src/shell/plugins/dws_environment.c
- t/t1004-dws-environment.t
Problem: as described in issue https://github.com/flux-framework/flux-coral2/issues/195, the dws_environment shell
plugin should call flux_job_event_watch_cancel after finding the
dws_environment event, otherwise the watch will stay active in
the job-info service, which will continue to send responses as new
events appear in the eventlog until the shell exits and a
disconnect message is sent.
Call flux_job_event_watch_cancel.
Fixes #195.
> Event watch cancel

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: kubernetes errors can make the coral2_dws service crash if they occur during a resource watch.
Add a try/except block around calls to reactor_run, catching exceptions coming from urllib3 and trying again after a timeout.
Fixes #197
> dws: add error-handling cycle for kubernetes

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/dws-dependencies/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: as rabbits enter more general use, there needs to be a way
to enforce crude limits on the size of file systems that users can
request.
Add command-line arguments to coral2_dws for accepting size limits
and logic to the directivebreakdown module for enforcing the limits.
The limits are enforced by adding an exception with a message while the job is held in DEPEND state.
> Enforce size constraints

- src/cmd/Makefile.am
- src/cmd/flux-dws2jgf.py
- src/cmd/flux-rabbitmapping.py
- src/python/flux_k8s/directivebreakdown.py
- t/data/dws2jgf/rabbits.json
- t/t1002-dws-workflow-obj.t
- t/t1003-dws-nnf-watch.t
- t/t2000-dws2jgf.t
Problem: as described in https://github.com/flux-framework/flux-coral2/issues/193, 
JGF is too unwieldy to be stored in Ansible. On the other hand, Flux's ability to start up and run
jobs cannot be dependent on the responsiveness of kubernetes, so generating JGF from kubernetes 
before starting Flux is not a good option.
The solution I've decided to go with after some discussion is to store some 
static rabbit layout data in ansible, generated by reading from kubernetes. This data in turn is then 
read in to generate JGF. Unlike kubernetes, we can expect the static file to always exist.
Fixes #193
> Dws: use static rabbit layout mapping for JGF

- t/sharness.d/02-flux-sharness.sh
- t/t1001-cray-pals.t
- t/t2000-dws2jgf.t
As @grondo mentioned [here](https://github.com/flux-framework/flux-coral2/pull/204#discussion_r1744383116), we can make `jq` a prereq for the entire testsuite and drop the `HAVE_JQ` prereq from individual test cases.
> testsuite: sharness sync

- src/modules/coral2_dws.py
Problem: the nnfdatamovement version has increased from v1alpha1 to v1alpha2. The next update may drop support for v1alpha1.
Increase the version to v1alpha2.
> dws: increase nnfdatamovement version

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
> dws: saving nnfdatamovements

- src/cmd/flux-dws2jgf.py
- src/modules/coral2_dws.py
Problem: sometimes users create workflows with nonsense jobids. For instance, on Tuolumne recently a user created a workflow with jobid "manual", crashing the service because the jobid could not be converted to a flux job ID.
Catch all exceptions that occur while trying to fetch basic data about a workflow and log them, but do not let them crash the service.
Exception seen:
```
Traceback (most recent call last):
File "/usr/bin/coral2_dws.py", line 945, in <module>
main()
File "/usr/bin/coral2_dws.py", line 936, in main
handle.reactor_run()
File "/usr/lib64/flux/python3.6/flux/core/handle.py", line 
Flux.raise_if_exception()
File "/usr/lib64/flux/python3.6/flux/core/handle.py", line 
raise cls.set_exception(None) from None
File "/usr/lib64/flux/python3.6/flux/core/watchers.py", line …
```
> dws: ignore bad jobids in workflows

- src/modules/coral2_dws.py
- t/scripts/sign-as.py
- t/t1002-dws-workflow-obj.t
Problem: until futher work is done to support various usage policies for persistent file systems, it is sometimes desirable to restrict their creation to the instance owner.
Reject jobs with `create_persistent` strings unless the job was submitted by the instance owner.
Add a flag to disable the check.
Fixes #205.
> dws: only allow owner to create persistent

- src/cmd/flux-dws2jgf.py
- t/data/dws2jgf/expected-compute-01-04.jgf
- t/data/dws2jgf/expected-compute-01-nodws.jgf
- t/data/dws2jgf/expected-compute-01.jgf
- t/data/dws2jgf/expected-properties.jgf
- t/t2000-dws2jgf.t
Problem: JGF is too large, as described in #193.
As a first step to shrink it, do not output default values, instead skipping them and letting the JGF reader supply them.
Depends on changes introduced in flux-sched by flux-framework/flux-sched/pull/1293. This will remain as a draft until that is merged.
> dws2jgf: drop defaults for jgf simplification

- src/modules/coral2_dws.py
Problem: on Tuolumne kubernetes was complaining that it could not interpret `None` as an int in a call to fetch datamovements.
Do not pass `None` as an argument.
> dws: fix datamovement limit call

- src/cmd/flux-dws2jgf.py
- t/data/dws2jgf/expected-configfile.jgf
- t/t2000-dws2jgf.t
Problem: the `capture_output` argument to subprocess.run requires python 3.7+ but LC machines are still on 3.6.
Replace the argument with a 3.6+ compatible equivalent.
> dws2jgf: remove python 3.7+ feature

- src/cmd/flux-rabbitmapping.py
- src/modules/coral2_dws.py
- src/python/flux_k8s/crd.py
flux-coral2 code in various places reads rabbit info (in particular, the mapping from compute nodes to rabbit nodes and vice versa) from `Storage` resources when it should instead read from the `Systemconfiguration` resource, which is comprehensive and static.
Fixes #221.
> dws: use systemconfiguration for rabbit mapping

- src/modules/coral2_dws.py
- t/data/workflow-obj/maximums/rabbit.toml
- t/t1002-dws-workflow-obj.t
- t/t1003-dws-nnf-watch.t
Moves a bunch of `coral2_dws.py` command-line arguments to a `[rabbit]` table in the Flux config.
See also https://github.com/flux-framework/flux-docs/pull/286 for a description of what the config file should look like.
Fixes #220.
> dws: rabbit config file support 

- src/modules/coral2_dws.py
- t/data/workflow-obj/maximums/rabbit.toml
- t/t1002-dws-workflow-obj.t
Problem: some users may not want to write custom #DW strings for
their jobs. It can take a while to learn the syntax and figure out
what options to use.
Add configurable preset #DW strings that can be defined in a config
file. Administrators can define some presets they think would work
for a large number of users of the system.
Fixes #200 .
> Rabbit preset dw strings

- src/cmd/flux-rabbitmapping.py
- src/modules/coral2_dws.py
- src/python/flux_k8s/Makefile.am
- src/python/flux_k8s/cleanup.py
Related to #159 and #197 . Add async routines to try to teardown and delete k8s workflows in an infinite loop until success.
> dws: retry k8s failures while cleaning up workflows

- src/cmd/flux-dws2jgf.py
- src/cmd/flux-rabbitmapping.py
Problem: an f-string in flux-dws2jgf is missing its `f` prefix, so an error message is not printed correctly.
Fix it, and remove some unused imports identified by pylint.
> dws2jgf: fix broken error message

- src/modules/coral2_dws.py
Problem: new releases of the DWS rabbit software stack have upped the recommended nnfdatamovement resource version from v1alpha2 to v1alpha4.
Change the version.
> dws: increase nnfdatamovement version to v1alpha4

- src/modules/coral2_dws.py
Problem: error messages produced by the coral2_dws script can be
extremely opaque.
Make them a little more verbose.
> dws: fix error messages

- src/job-manager/plugins/dws-jobtap.c
- t/t1002-dws-workflow-obj.t
Problem: The dws-jobtap plugin does not use the jobspec update
jobtap interface to perform its update of a job's resources. Instead
it simply grabs the jobspec directly and manipulates it. However, it
would be good for users to have a record of how their jobspec was
changed, and doing so may prevent problems in the future.
Make dws-jobtap use the jobspec update interface.
Fixes https://github.com/flux-framework/flux-coral2/issues/158
> dws: rabbit resources jobspec update

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- t/dws-dependencies/coral2_dws.py
- t/t1003-dws-nnf-watch.t
Problem: Fluxion continues to have problems with rabbits on
production systems. However, users need a way for Flux to
automatically schedule around down rabbits.
As a workaround, maintain a hostlist of all nodes that are attached
to down rabbits. Add this hostlist to jobs' constraints, as a negative hostlist constraint (like
`--requires=-hosts:foobar[1-20]`)
> dws: add negative requires hostlist for down rabbits

- NEWS.md
Problem: there are no release notes for v0.19.1.
Add them.
> NEWS.md: add release notes for v0.19.1

- src/modules/coral2_dws.py
Problem: 'rabbit.mapping' is rejected by coral2_dws as a config key, but it is valid.
Make coral2_dws accept it.
> dws: add 'mapping' to accepted config keys

- src/modules/coral2_dws.py
Problem: if unexpected keys are found in the `rabbit` config table, coral2_dws exits with an error. This is probably overkill.
Instead, issue a warning.
> dws: make config error a warning

- src/cmd/flux-getrabbit.py
- t/t2001-getrabbit.t
Problem: there is no way to get a list of all rabbit nodes from
the `flux getrabbit` command.
Make it so that passing no arguments to `getrabbit` makes it print
a hostlist of all rabbits.
> `getrabbit`: list all rabbits

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- t/t1003-dws-nnf-watch.t
Problem: Fluxion continues to have problems with rabbits on
production systems. However, users need a way for Flux to
automatically schedule around down rabbits.
Previously (see #252), a hostlist constraint was used. However, that doesn't
work very well when queue times are long, because rabbit status can
change while the job sits in the queue.
Instead, use a property constraint.
> dws: change exclusion constraint to a property 

- src/cmd/flux-getrabbit.py
- t/t2001-getrabbit.t
Problem: `flux getrabbit` could save users a bit of work by accepting
job IDs.
Make it take job IDs.
Closes #268 .
> rabbitmapping: fetch by jobid

- src/cmd/flux-getrabbit.py
- t/t2001-getrabbit.t
Problem: https://github.com/flux-framework/flux-coral2/pull/272 added a way to look up the rabbits for a job. It works correctly in all cases, however in the future for lustre file systems, the rabbits associated with a job may no longer be the rabbits local to the compute nodes in the job.
There is already [a memo](https://github.com/flux-framework/flux-coral2/blob/8abdb50447589c20985777da9347ffb2db0891ba/src/modules/coral2_dws.py#L319) associated with every rabbit job, specifying what rabbits are used. That should be used instead.
Fixes #275 .
> `getrabbit`: jobid memo lookups

- NEWS.md
Problem: there are no release notes for v0.20.1.
Add them.
> NEWS.md: add release notes for v0.20.1

- src/modules/coral2_dws.py
Two small fixes, and one kinda messy refactoring that doesn't change any functionality.
> `coral2_dws`: refactor badrabbit property

- src/job-manager/plugins/dws-jobtap.c
Problem: as described in #285, the `dws-jobtap` plugin creates a boolean jobtap aux to indicate whether or not the prolog it sets on jobs is still active, but it creates the aux in the DEPEND state despite the fact that it will not start the prolog until the RUN state. If Flux is restarted with jobs in the queue, the aux will be lost and a lookup for the aux will cause the RUN callback to fail.
Only set the `prolog_active` aux at the time that the prolog is actually started, and not before.
Fixes #285.
> dws-jobtap: avoid setting aux too early

- src/modules/coral2_dws.py
- src/python/flux_k8s/watch.py
Problem: kubernetes documentation states that objects' resourceVersion fields should NOT be cast to an integer and compared. However, coral2_dws does exactly that.
Remove the cast and comparison, since it is not needed.
> dws: stop casting k8s resourceVersion to int

- src/modules/coral2_dws.py
- src/python/flux_k8s/workflow.py
`coral2_dws` logs some very verbose messages which clutter the logs, and are unhelpful for debugging. It also includes kubernetes log messages when it attempts to set its own log level to `LOG_DEBUG`.
> dws: drop unnecessary log messages

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- t/dws-dependencies/coral2_dws.py
- t/t1000-dws-dependencies.t
Similarly to #286, remove a jobtap aux that is set to indicate that a workflow has been created for a job. This aux would cause problems if the plugin were reloaded, so this PR re-architects things so that it is not needed.
> dws: remove create callback jobtap aux

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- t/dws-dependencies/coral2_dws.py
Problem: the `dws-jobtap` plugin does not respond to the RPCs it
receives. This could lead to the buildup of matchtags in the sender,
in this case `coral2_dws.py`.
Add handling for responding to all RPCs received.
> dws-jobtap: rpc responses

- NEWS.md
Problem: there are no release notes for v0.21.0.
Add them.
Waiting on #304.
> NEWS.md: add release notes for v0.21.0

- configure.ac
- src/common/Makefile.am
- src/common/libapinfo/Makefile.am
- src/common/libapinfo/apimpl.h
- src/common/libapinfo/apinfo.c
- src/common/libapinfo/apinfo.h
- src/common/libapinfo/apinfo1.c
- src/common/libapinfo/apinfo1.h
- src/common/libapinfo/test/apinfo.c
- src/common/libapinfo/test/pals.c
- src/common/libutil/Makefile.am
- src/common/libutil/errprintf.c
- src/common/libutil/errprintf.h
- src/shell/plugins/Makefile.am
- src/shell/plugins/cray_pals.c
This pulls out the apinfo v1 stuff from the `cray_pals` shell plugin, refactors it, and puts it in a convenience library with unit tests.  I think it'll be pretty easy to add apinfo v5 support as proposed in #282 with a way to fall back to the well tested v1 at runtime.
One thing I did not quite understand - what is the `cpus_per_pe` parameter used for?  I can't for the life of me think why a PMI would need to know how many cpus per task there are, but it'll probably be a "duh" moment when someone tells me.
I did add a test using `libpals` as suggested by HPE although obviously we can't run it in CI at this point.  (It isn't compiled if libpals is unavailable).
Marking WIP pending end to end manual  testing on El Cap.
> add libapinfo convenience library

- src/common/libapinfo/Makefile.am
- src/common/libapinfo/apinfo.c
- src/common/libapinfo/apinfo1.c
- src/common/libapinfo/apinfo5.c
- src/common/libapinfo/apinfo5.h
- src/common/libapinfo/test/apinfo.c
- src/common/libapinfo/test/pals.c
- src/shell/plugins/cray_pals.c
- t/t1001-cray-pals.t
This moves apinfo to v5 (as first demonstrated in @jameshcorbett 's #282 ), with an option to fall back to v1.
The fallback option is `-o cray-pals.apinfo-version=1`
> cray_pals: use apinfo v5

- .readthedocs.yaml
Problem: sphinx attempts to import the `imghdr` standard library, but it was removed in Python 3.13+. The readthedocs builder uses 3.13.
Downgrade the builder to 3.12.
Another option would have been to upgrade sphinx, because newer versions no longer import `imghdr`, but flux projects universally require sphinx version < 6.0.0, and it seemed desirable to maintain consistency of sphinx versioning.
See e.g. https://app.readthedocs.org/projects/flux-coral2/builds/27470351/
> readthedocs: fix imghdr not found error

- .github/workflows/main.yml
Problem: github workflows don't run in feature branches of private forks.
Change the rules so that ci runs on branches other than master.
Fixes #317
> github: run workflow on push to any branch

- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: a job with invalid #DW directives currently results in log messages at level ERROR, but really it is a user error and should at most be DEBUG or INFO.
Intercept the problem and raise a UserError instead which will not be logged.
> dws: fix error logging for invalid directives

- doc/guide/reference.rst
- doc/man1/flux-shell-cray-pals.rst
- doc/test/spell.en.pws
Problem: we have no docs on the rabbits.
@behlendorf pointed me to a Lustre Users Group presentation that contains detail about the hardware and intended use cases. 
Add this to the References section.
Also, I noticed I missed an option in flux-shell-cray-pals(1), so add that.
> doc: add a rabbit ref, and improve cray-pals man page

- debian/control
- doc/man1/flux-shell-cray-pals.rst
- doc/test/spell.en.pws
- src/common/libutil/Makefile.am
- src/common/libutil/eventlog.c
- src/common/libutil/eventlog.h
- src/shell/plugins/Makefile.am
- src/shell/plugins/cray_pals.c
- src/shell/plugins/dws_environment.c
- t/sharness.d/02-flux-sharness.sh
- t/t1001-cray-pals.t
Problem: cray-pals isn't set up very well for being extended, and we may need to do some work in it to support VNIs and to improve the port distribution mechanism.
Refactor the plugin to add a global state container that reduces some complexity and provides a way to hold future items that can have their life cycle tied to plugin loading.
Tighten up option parsing.  Add an option to set the pmi port and secret, and then decouple that from the eventlog watching somewhat, so that we can add a collective based method later more easily.
I've played with this a bit and also tested on El Cap with a couple of nodes.  Pretty sure I didn't break anything :-)
> cray-pals: refactor and add test options

- src/python/flux_k8s/directivebreakdown.py
- t/data/breakdown/lustre10gb_count2.yaml
- t/python/t0001-directive-breakdown.py
Problem: when an explicit allocationCount is requested in a storage profile, `directivebreakdown.py` sometimes lays out the storage in a way that causes an error.
Fix it.
Fixes #322.
> directivebreakdown: condense allocationCount

- NEWS.md
Problem: there are no release notes for v0.22.0.
Add them.
> NEWS.md: add release notes for v0.22.0

- doc/guide/rabbit.rst
- src/modules/coral2_dws.py
- src/python/flux_k8s/Makefile.am
- src/python/flux_k8s/crd.py
- src/python/flux_k8s/storage.py
- src/python/flux_k8s/systemstatus.py
- t/t1003-dws-nnf-watch.t
As described in #341, DWS needs Flux to tell it what nodes are up or down so it can potentially forget about some rabbit file system mounts, allowing jobs to clean up.
Fixes #341 .
> dws: update dws systemstatus resource

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
Problem: in `cleanup_cb`, there are multiple `return` statements after some memory has been allocated but before the memory is set to a jobtap aux for automatic deletion. Those `return` statements would therefore cause the memory to be leaked.
Assign the memory to a jobtap aux at the time of allocation.
> dws: fix memory leak in callback

- doc/Makefile.am
- doc/conf.py
- doc/guide/rabbit_config.rst
- doc/man1/flux-jobtap-dws.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: PR https://github.com/flux-framework/flux-coral2/pull/336 added an epilog timeout for moving a workflow to
teardown, as well as removing the epilog and potentially draining
nodes and disabling rabbits. However, before taking that drastic step
it makes sense to move a workflow to Teardown to give it a chance
to clean up. In theory, this could make it so the epilog timeout
never hits or at least reduce the number of rabbits disabled when
the timeout hits.
Add a timer-watcher that moves a workflow to Teardown.
> dws: teardown timeout

- doc/guide/rabbit_config.rst
- src/modules/coral2_dws.py
- src/python/flux_k8s/systemstatus.py
- src/python/flux_k8s/workflow.py
- t/t1002-dws-workflow-obj.t
- t/t1003-dws-nnf-watch.t
There have recently been several issues on elcap clusters where rabbit workflows were stuck in the `PostRun` state waiting for nodes to unmount file systems. Some of them had a hung mount point. Flux needs a way to abandon mounts and drain nodes when this happens, and this PR implements that.
> dws: postrun timeout

- src/job-manager/plugins/dws-jobtap.c
- src/modules/coral2_dws.py
- src/python/flux_k8s/directivebreakdown.py
- t/dws-dependencies/coral2_dws.py
- t/python/t0001-directive-breakdown.py
- t/t1002-dws-workflow-obj.t
Problem: as mentioned in https://github.com/flux-framework/flux-coral2/issues/257, the copy-offload daemon no longer
needs to be supported, and is already removed from TOSS 4.8-11.
Prolog and epilog scripts will no longer check for the copy_offload
context in dws_environment events.
Remove all related logic.
Fixes #257 .
> dws: drop copy offload

- doc/guide/admin.rst
Problem: as described in PR #342, two exceptions are required to maximally expedite rabbit cleanup.
Document that fact.
> docs: document double cancellation behavior

- doc/guide/rabbit_config.rst
Problem: the docs have a broken link and some incorrect formatting, putting some words in single backticks rather than double.
Fix them.
> doc: fix link and style

- src/modules/coral2_dws.py
Problem: the pstats SortKey enum was introduced in Python 3.7, but code must support 3.6.
Use a string instead of the SortKey enum.
> dws: remove python 3.7 feature

- NEWS.md
Problem: there are no release notes for v0.25.0.
Add them.
> NEWS.md: add release notes for v0.25.0

- doc/guide/rabbit.rst
- doc/guide/reference.rst
Problem: there should be more references to the HPE rabbit
documentation in this repo's rabbit docs, because the HPE docs have
a lot of additional detail. Currently there is only one link.
Add more links.
> docs: add rabbit references

- etc/flux-coral2-dws.service.in
Problem: the systemd watchdog introduced in PR #374 has a typo.
Fix it.
See https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#WatchdogSec=
> dws: fix typo in systemd unit file

- src/job-manager/plugins/dws-jobtap.c
- t/t1000-dws-dependencies.t
Problem: when the dws-jobtap plugin is reloaded, as e.g. happens on
restart, the plugin will no longer receive exception event
notifications for jobs that existed before the reload, because the
only call to `flux_jobtap_job_subscribe` happens in the `DEPEND`
state callback. This means jobs can get stuck in prologs and epilogs.
Add a call to `flux_jobtap_job_subscribe` in the RUN callback as well.
Fixes #379.
> dws: jobtap event resubscribe

- src/modules/coral2_dws.py
- src/python/flux_k8s/cleanup.py
Problem: the `save_pod_log` function of the `flux_k8s.cleanup` module
sometimes raises exceptions, but the tracebacks are lost.
Log exceptions from the function.
> dws: exceptions raised while fetching pod logs are lost

- Makefile.am
- doc/guide/rabbit.rst
- doc/test/spell.en.pws
- etc/01-rabbit-rc
- t/t1002-dws-workflow-obj.t
PR #385 added all the infrastructure to identify nodes with rabbit failures and nevertheless allow jobs to proceed through them. However, there still needs to be some action taken on the nodes with failures. This PR adds a rc1 script that drains nodes. In the future, it might be better to move the nodes to a separate queue, so that they are still available for use. However, that will be left for a later release.
Related to #364.
> dws: add rc1 script to drain nodes with rabbit failures

- NEWS.md
Problem: there are no release notes for v0.26.0.
Add them.
Waiting on #385.
> NEWS.md: add release notes for v0.26.0

- t/rc/rc1-job
- t/rc/rc3-job
Problem: the flux-core barrier module is deprecated, but is loaded in test.
Don't load it.  It is unused by flux-coral2.
> testsuite: don't load deprecated barrier module

- src/python/flux_k8s/crd.py
- src/python/flux_k8s/directivebreakdown.py
Problem: there is a new dataworkflowservices.github.io API version, `v1alpha6`.
Use the new version.
Keeping this as WIP until some substantial number of LC clusters are actually serving `v1alpha6`, which might be a while.
> dws: upgrade to dws api v1alpha6

- etc/01-rabbit-rc
Problem: 01-rabbit-rc uses a bash [[ ]] test but its shebang invokes sh, which is not portable.
On debian, where sh -> dash, this fails with
broker.err[0]: rc1.0: /etc/flux/rc1.d/01-rabbit-rc: 3: [[: not found
Admittedly this is a coral2 specific package, but it is helpful to be able to install it on debian test systems.
> rc: avoid unportable bashism

- etc/01-rabbit-rc
- src/cmd/flux-dws2jgf.py
- src/modules/coral2_dws.py
- t/t1002-dws-workflow-obj.t
Problem: the timer for the `PreRun` state cancels a job if it gets stuck in that state for too long. However, the timer is not cleared when the state completes successfully, so jobs can be canceled improperly if they run for any considerable length of time.
Stop the timer when `PreRun` state completes.
> dws: stop prerun timer once state completes

- NEWS.md
Problem: there are no release notes for v0.27.0.
Add them.
> NEWS.md: add release notes for v0.27.0

- src/modules/coral2_dws.py
Problem: a conditional raises a fatal exception on a job, and should then return from the function because additional processing is not necessary. However, there is no return statement.
Add the missing `return`.
> coral2_dws: add missing return statement

- .typos.toml
- scripts/build-libcxi.sh
- scripts/install-libcxi-deps-deb.sh
- scripts/install-libcxi.sh
- src/cmd/flux-slingshot.c
- src/test/docker/noble/Dockerfile
Problem: conditionally compiled slingshot support isn't even compile-tested in CI.
Build the open source libcxi and install it in the `noble` Docker image so we can do a compile test on at least one platform.  Our software won't find any slingshot devices but at least we can find compilation issues.
The docker image uses the `release/shs-13.0` branch to hopefully maintain stability moving forward (there are no tags in that repo).  Some scripts are also added that can install the main development branch on a test system if desired.
> ci: add libcxi to one of the docker builds

- doc/guide/slingshot.rst
- src/shell/plugins/cray-slingshot.c
- t/t3001-slingshot-shell.t
Problem: the cray-slingshot shell plugin does not set SLINGSHOT_TCS in the job environment, but Cray MPICH does use it if set.
Set it as discussed in #412
> set SLINGSHOT_TCS in job environment

- src/cmd/flux-slingshot.c
- src/job-manager/plugins/cray-slingshot.c
- src/job-manager/plugins/vnipool.h
- t/t3002-slingshot-cmd.t
Problem: `flux slingshot clean` doesn't know that there is now a default vni pool config.
Fix that.
Note that this isn't even used yet because it's a little scary.  At this point the housekeeping script just runs `flux slingshot epilog` with a longer `--retry-busy` duration than the epilog script.  IOW it only removes CXI services for the job that triggered housekeeping.  `clean` would remove _all_ CXI services matching Flux's VNI pool on the assumption that the node is exclusively scheduled and none should be active at that point.
> flux-slingshot clean: fall back to default pool config
